### ISSUE TITLE
No data if symbol inexistent

### ISSUE THREAD

**Issue by christiandavidfs** [christiandavidfs/pythonapi#1]
When the user pass a symbol that don't exist, the response send fields with None data, for example: 
for: FB

{'high': {'date': None, 'price': None, 'value': 0.0, 'shares': 0.0}, 'low': {'date': None, 'price': None, 'value': 0.0, 'shares': 0.0}}

It's that correct?

**Comment by melvin-mbww** [comment]
Created #3 to address this issue
