### ISSUE TITLE
Some stocks show error code only in the CSV

### ISSUE THREAD

**Issue by christiandavidfs** [christiandavidfs/pythonapi#2]
http://stock-whatif.herokuapp.com/whatif/ACAD/raw

The data shown in the screen shows no data, but when looking to the csv you find a message:

QEPx04
--

You do not have   permission to view this dataset. Please subscribe to this database to get   access.
--

[ACAD.txt](https://github.com/christiandavidfs/pythonapi/files/2605533/ACAD.txt)

**Comment by melvin-mbww** [comment]
See issue #3
